[project]
name = "python-hello-world"
version = "0.1.0"
description = "A hello world built in Python also making use of pydantic to connect to an SQL DB"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=44.0.2",
    "pymysql>=1.1.1",
    "sqlalchemy>=2.0.38",
]

